version: '3.9'
services:
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    labels:
      - "traefik.http.middlewares.auth.basicauth.usersfile=/path/to/.htpasswd"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data
    ports:
      - "9000:9000"

  app:
    build: .
    environment:
      # アプリケーションの環境変数設定
    depends_on:
      - minio
      - traefik