version: '3.8'
services:
  web:
    image: python:3.11
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db:5432/app_db
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db

  redis:
    image: redis:7