name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

concurrency:
  # mainブランチへのデプロイは直列実行
  group: deploy-main
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production  # 環境保護ルールがある場合有効
    steps:
      - uses: actions/checkout@v3

      # Dockerビルドを効率化するためのQEMUセットアップ（必要な場合のみ）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Dockerメタデータ抽出で、Git SHAやタグに応じたイメージタグ付与
      - name: Extract Docker metadata (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: user/repository
          tags: |
            type=ref,event=branch
            type=sha
            type=ref,event=tag

      # Dockerビルド&プッシュ
      # GitHub Actions Cacheを活用してビルド時間短縮
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Blue/Greenデプロイ用スクリプトを実行（例）
      - name: Deploy (Blue/Green)
        run: ./scripts/deploy_blue_green.sh
